export const INDIAN_UNIVERSITIES = [
  "Lucknow University",
  "IIT Delhi",
  "IIT Bombay",
  "IIT Kanpur",
  "IIT Madras",
  "IIT Kharagpur",
  "IIT Roorkee",
  "IIT Guwahati",
  "IIT Hyderabad",
  "IIT BHU",
  "IIT Indore",
  "IIT Patna",
  "IIT Bhubaneswar",
  "IIT Gandhinagar",
  "IIT Jodhpur",
  "IIT Mandi",
  "IIT Palakkad",
  "IIT Tirupati",
  "IIT Bhilai",
  "IIT Dharwad",
  "IIT Goa",
  "IIT Jammu",
  "IIM Ahmedabad",
  "IIM Bangalore",
  "IIM Calcutta",
  "IIM Lucknow",
  "IIM Kozhikode",
  "IIM Indore",
  "IIM Shillong",
  "IIM Raipur",
  "IIM Ranchi",
  "IIM Rohtak",
  "IIM Kashipur",
  "IIM Udaipur",
  "IIM Tiruchirappalli",
  "IIM Bodh Gaya",
  "IIM Sirmaur",
  "IIM Nagpur",
  "IIM Amritsar",
  "IIM Sambalpur",
  "IIM Visakhapatnam",
  "NIT Trichy",
  "NIT Surathkal",
  "NIT Warangal",
  "NIT Kurukshetra",
  "NIT Allahabad",
  "NIT Calicut",
  "NIT Jaipur",
  "NIT Silchar",
  "NIT Nagpur",
  "NIT Bhopal",
  "NIT Durgapur",
  "NIT Jamshedpur",
  "NIT Patna",
  "NIT Raipur",
  "NIT Agartala",
  "NIT Arunachal Pradesh",
  "NIT Delhi",
  "NIT Goa",
  "NIT Hamirpur",
  "NIT Manipur",
  "NIT Meghalaya",
  "NIT Mizoram",
  "NIT Nagaland",
  "NIT Puducherry",
  "NIT Sikkim",
  "NIT Tripura",
  "NIT Uttarakhand",
  "DU",
  "University of Delhi",
  "St. Stephen's College",
  "Hindu College",
  "Miranda House",
  "Shri Ram College of Commerce",
  "Hansraj College",
  "Ramjas College",
  "Kirori Mal College",
  "Sri Venkateswara College",
  "Gargi College",
  "Indian School of Business (ISB)",
  "JNU",
  "Jawaharlal Nehru University",
  "Jamia Millia Islamia",
  "AMU",
  "Aligarh Muslim University",
  "BHU",
  "Banaras Hindu University",
  "Punjab University",
  "Chandigarh University",
  "VIT",
  "VIT Vellore",
  "VIT Chennai",
  "SRM University",
  "SRM Institute of Science and Technology",
  "Manipal University",
  "Manipal Academy of Higher Education",
  "BITS Pilani",
  "BITS Goa",
  "BITS Hyderabad",
  "Anna University",
  "Andhra University",
  "JNTU",
  "Jawaharlal Nehru Technological University",
  "TISS",
  "Tata Institute of Social Sciences",
  "XLRI",
  "XLRI - Xavier School of Management",
  "NIFT",
  "National Institute of Fashion Technology",
  "ICAI",
  "Institute of Chartered Accountants of India",
  "ICMAI",
  "Institute of Cost Accountants of India",
  "CSI",
  "NIMC",
  "IISc Bangalore",
  "Indian Institute of Science",
  "IISER Pune",
  "IISER Kolkata",
  "IISER Mohali",
  "IISER Bhopal",
  "IISER Thiruvananthapuram",
  "IISER Tirupati",
  "IISER Berhampur"
] as const;
