import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { useAnalysisStore } from "@/store/analysisStore";
import { useAuth } from "@/contexts/AuthContext";
import { fetchAnalysisById } from "@/lib/supabase/analysis-db";
import { ResultPage } from "./result";
import { AppShell } from "@/components/app-shell";
import { Card, CardContent } from "@/components/ui/card";
import { Loader2 } from "lucide-react";
import { createSeoHead, ORGANIZATION_SCHEMA } from "@/lib/seo";

export const Route = createFileRoute("/report/$id")({
  async loader({ params }) {
    try {
      const analysis = await fetchAnalysisById(params.id);
      return { analysis };
    } catch (e) {
      console.error(e);
      return { analysis: null };
    }
  },
  head: ({ loaderData }) => {
    const analysis = loaderData?.analysis;
    if (!analysis) {
      return createSeoHead({
        title: "Report Not Found",
        description: "Resume report not found.",
        path: "/report/not-found",
        noindex: true,
      });
    }
    return createSeoHead({
      title: `ATS Report for ${analysis.role} Resume`,
      description: "View this ATS analysis report generated by ResumePilot.",
      path: `/report/${analysis.id}`,
      noindex: !analysis.is_public,
      schema: {
        "@context": "https://schema.org",
        "@graph": [ORGANIZATION_SCHEMA],
      },
    });
  },
  component: ReportPage,
});

function ReportPage() {
  const { id } = Route.useParams();
  const navigate = useNavigate();
  const { user } = useAuth();
  const { setResult, hasResult } = useAnalysisStore();
  const loaderData = Route.useLoaderData();
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [analysis, setAnalysis] = useState<any>(loaderData?.analysis);

  useEffect(() => {
    if (loaderData?.analysis) {
      setAnalysis(loaderData.analysis);
      setResult(
        loaderData.analysis.analysis_result,
        loaderData.analysis.role,
        loaderData.analysis.file_name,
        loaderData.analysis.resume_text || "",
        loaderData.analysis.job_description ?? undefined,
        {
          animateEntry: false,
          analysisId: loaderData.analysis.id,
          isSaved: loaderData.analysis.is_saved,
          isPublic: loaderData.analysis.is_public,
          interviewQuestions: loaderData.analysis.interview_questions || undefined,
        }
      );
      setIsLoading(false);
    } else {
      setError("Report not found");
      setIsLoading(false);
    }
  }, [loaderData, setResult]);

  if (isLoading) {
    return (
      <AppShell>
        <div className="flex items-center justify-center py-20">
          <Loader2 className="h-8 w-8 animate-spin" />
        </div>
      </AppShell>
    );
  }

  if (error) {
    return (
      <AppShell>
        <Card className="border-border/60">
          <CardContent className="flex flex-col items-center justify-center py-16 text-center">
            <p className="mt-3 font-semibold">{error}</p>
            <button
              onClick={() => navigate({ to: "/upload" })}
              className="mt-4 text-sm text-primary underline"
            >
              Upload a new resume
            </button>
          </CardContent>
        </Card>
      </AppShell>
    );
  }

  if (hasResult && analysis) {
    return <ResultPage />;
  }

  return null;
}
