/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SoftwareEngineerResumeTemplateRouteImport } from './routes/software-engineer-resume-template'
import { Route as ResumeScoreCheckerRouteImport } from './routes/resume-score-checker'
import { Route as ResultRouteImport } from './routes/result'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MockInterviewRouteImport } from './routes/mock-interview'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobMatchRouteImport } from './routes/job-match'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FresherResumeTemplateRouteImport } from './routes/fresher-resume-template'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DataDeletionRouteImport } from './routes/data-deletion'
import { Route as DataAnalystResumeTemplateRouteImport } from './routes/data-analyst-resume-template'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoverLetterRouteImport } from './routes/cover-letter'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as AtsResumeCheckerRouteImport } from './routes/ats-resume-checker'
import { Route as AiInterviewQuestionsRouteImport } from './routes/ai-interview-questions'
import { Route as AiCoverLetterGeneratorRouteImport } from './routes/ai-cover-letter-generator'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ReportIdRouteImport } from './routes/report.$id'
import { Route as MobileToolsRouteImport } from './routes/mobile.tools'
import { Route as MobileRequestFeatureRouteImport } from './routes/mobile.request-feature'
import { Route as MobileInsightsRouteImport } from './routes/mobile.insights'
import { Route as MobileBetaProgramRouteImport } from './routes/mobile.beta-program'
import { Route as InterviewReportIdRouteImport } from './routes/interview-report.$id'
import { Route as DashboardSecurityRouteImport } from './routes/dashboard.security'
import { Route as DashboardSavedRouteImport } from './routes/dashboard.saved'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardInterviewsRouteImport } from './routes/dashboard.interviews'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard.history'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareEngineerResumeTemplateRoute =
  SoftwareEngineerResumeTemplateRouteImport.update({
    id: '/software-engineer-resume-template',
    path: '/software-engineer-resume-template',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResumeScoreCheckerRoute = ResumeScoreCheckerRouteImport.update({
  id: '/resume-score-checker',
  path: '/resume-score-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MockInterviewRoute = MockInterviewRouteImport.update({
  id: '/mock-interview',
  path: '/mock-interview',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobMatchRoute = JobMatchRouteImport.update({
  id: '/job-match',
  path: '/job-match',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FresherResumeTemplateRoute = FresherResumeTemplateRouteImport.update({
  id: '/fresher-resume-template',
  path: '/fresher-resume-template',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDeletionRoute = DataDeletionRouteImport.update({
  id: '/data-deletion',
  path: '/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const DataAnalystResumeTemplateRoute =
  DataAnalystResumeTemplateRouteImport.update({
    id: '/data-analyst-resume-template',
    path: '/data-analyst-resume-template',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverLetterRoute = CoverLetterRouteImport.update({
  id: '/cover-letter',
  path: '/cover-letter',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const AtsResumeCheckerRoute = AtsResumeCheckerRouteImport.update({
  id: '/ats-resume-checker',
  path: '/ats-resume-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInterviewQuestionsRoute = AiInterviewQuestionsRouteImport.update({
  id: '/ai-interview-questions',
  path: '/ai-interview-questions',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCoverLetterGeneratorRoute = AiCoverLetterGeneratorRouteImport.update({
  id: '/ai-cover-letter-generator',
  path: '/ai-cover-letter-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ReportIdRoute = ReportIdRouteImport.update({
  id: '/report/$id',
  path: '/report/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileToolsRoute = MobileToolsRouteImport.update({
  id: '/mobile/tools',
  path: '/mobile/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRequestFeatureRoute = MobileRequestFeatureRouteImport.update({
  id: '/mobile/request-feature',
  path: '/mobile/request-feature',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileInsightsRoute = MobileInsightsRouteImport.update({
  id: '/mobile/insights',
  path: '/mobile/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileBetaProgramRoute = MobileBetaProgramRouteImport.update({
  id: '/mobile/beta-program',
  path: '/mobile/beta-program',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewReportIdRoute = InterviewReportIdRouteImport.update({
  id: '/interview-report/$id',
  path: '/interview-report/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSecurityRoute = DashboardSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSavedRoute = DashboardSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInterviewsRoute = DashboardInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-cover-letter-generator': typeof AiCoverLetterGeneratorRoute
  '/ai-interview-questions': typeof AiInterviewQuestionsRoute
  '/ats-resume-checker': typeof AtsResumeCheckerRoute
  '/coming-soon': typeof ComingSoonRoute
  '/cover-letter': typeof CoverLetterRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/data-analyst-resume-template': typeof DataAnalystResumeTemplateRoute
  '/data-deletion': typeof DataDeletionRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/fresher-resume-template': typeof FresherResumeTemplateRoute
  '/how-it-works': typeof HowItWorksRoute
  '/job-match': typeof JobMatchRoute
  '/login': typeof LoginRoute
  '/mock-interview': typeof MockInterviewRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/result': typeof ResultRoute
  '/resume-score-checker': typeof ResumeScoreCheckerRoute
  '/software-engineer-resume-template': typeof SoftwareEngineerResumeTemplateRoute
  '/terms': typeof TermsRoute
  '/upload': typeof UploadRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/interviews': typeof DashboardInterviewsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/saved': typeof DashboardSavedRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/interview-report/$id': typeof InterviewReportIdRoute
  '/mobile/beta-program': typeof MobileBetaProgramRoute
  '/mobile/insights': typeof MobileInsightsRoute
  '/mobile/request-feature': typeof MobileRequestFeatureRoute
  '/mobile/tools': typeof MobileToolsRoute
  '/report/$id': typeof ReportIdRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-cover-letter-generator': typeof AiCoverLetterGeneratorRoute
  '/ai-interview-questions': typeof AiInterviewQuestionsRoute
  '/ats-resume-checker': typeof AtsResumeCheckerRoute
  '/coming-soon': typeof ComingSoonRoute
  '/cover-letter': typeof CoverLetterRoute
  '/data-analyst-resume-template': typeof DataAnalystResumeTemplateRoute
  '/data-deletion': typeof DataDeletionRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/fresher-resume-template': typeof FresherResumeTemplateRoute
  '/how-it-works': typeof HowItWorksRoute
  '/job-match': typeof JobMatchRoute
  '/login': typeof LoginRoute
  '/mock-interview': typeof MockInterviewRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/result': typeof ResultRoute
  '/resume-score-checker': typeof ResumeScoreCheckerRoute
  '/software-engineer-resume-template': typeof SoftwareEngineerResumeTemplateRoute
  '/terms': typeof TermsRoute
  '/upload': typeof UploadRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/interviews': typeof DashboardInterviewsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/saved': typeof DashboardSavedRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/interview-report/$id': typeof InterviewReportIdRoute
  '/mobile/beta-program': typeof MobileBetaProgramRoute
  '/mobile/insights': typeof MobileInsightsRoute
  '/mobile/request-feature': typeof MobileRequestFeatureRoute
  '/mobile/tools': typeof MobileToolsRoute
  '/report/$id': typeof ReportIdRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-cover-letter-generator': typeof AiCoverLetterGeneratorRoute
  '/ai-interview-questions': typeof AiInterviewQuestionsRoute
  '/ats-resume-checker': typeof AtsResumeCheckerRoute
  '/coming-soon': typeof ComingSoonRoute
  '/cover-letter': typeof CoverLetterRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/data-analyst-resume-template': typeof DataAnalystResumeTemplateRoute
  '/data-deletion': typeof DataDeletionRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/fresher-resume-template': typeof FresherResumeTemplateRoute
  '/how-it-works': typeof HowItWorksRoute
  '/job-match': typeof JobMatchRoute
  '/login': typeof LoginRoute
  '/mock-interview': typeof MockInterviewRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/result': typeof ResultRoute
  '/resume-score-checker': typeof ResumeScoreCheckerRoute
  '/software-engineer-resume-template': typeof SoftwareEngineerResumeTemplateRoute
  '/terms': typeof TermsRoute
  '/upload': typeof UploadRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/interviews': typeof DashboardInterviewsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/saved': typeof DashboardSavedRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/interview-report/$id': typeof InterviewReportIdRoute
  '/mobile/beta-program': typeof MobileBetaProgramRoute
  '/mobile/insights': typeof MobileInsightsRoute
  '/mobile/request-feature': typeof MobileRequestFeatureRoute
  '/mobile/tools': typeof MobileToolsRoute
  '/report/$id': typeof ReportIdRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-cover-letter-generator'
    | '/ai-interview-questions'
    | '/ats-resume-checker'
    | '/coming-soon'
    | '/cover-letter'
    | '/dashboard'
    | '/data-analyst-resume-template'
    | '/data-deletion'
    | '/faq'
    | '/features'
    | '/fresher-resume-template'
    | '/how-it-works'
    | '/job-match'
    | '/login'
    | '/mock-interview'
    | '/privacy'
    | '/reset-password'
    | '/result'
    | '/resume-score-checker'
    | '/software-engineer-resume-template'
    | '/terms'
    | '/upload'
    | '/auth/callback'
    | '/dashboard/history'
    | '/dashboard/interviews'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/saved'
    | '/dashboard/security'
    | '/interview-report/$id'
    | '/mobile/beta-program'
    | '/mobile/insights'
    | '/mobile/request-feature'
    | '/mobile/tools'
    | '/report/$id'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-cover-letter-generator'
    | '/ai-interview-questions'
    | '/ats-resume-checker'
    | '/coming-soon'
    | '/cover-letter'
    | '/data-analyst-resume-template'
    | '/data-deletion'
    | '/faq'
    | '/features'
    | '/fresher-resume-template'
    | '/how-it-works'
    | '/job-match'
    | '/login'
    | '/mock-interview'
    | '/privacy'
    | '/reset-password'
    | '/result'
    | '/resume-score-checker'
    | '/software-engineer-resume-template'
    | '/terms'
    | '/upload'
    | '/auth/callback'
    | '/dashboard/history'
    | '/dashboard/interviews'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/saved'
    | '/dashboard/security'
    | '/interview-report/$id'
    | '/mobile/beta-program'
    | '/mobile/insights'
    | '/mobile/request-feature'
    | '/mobile/tools'
    | '/report/$id'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-cover-letter-generator'
    | '/ai-interview-questions'
    | '/ats-resume-checker'
    | '/coming-soon'
    | '/cover-letter'
    | '/dashboard'
    | '/data-analyst-resume-template'
    | '/data-deletion'
    | '/faq'
    | '/features'
    | '/fresher-resume-template'
    | '/how-it-works'
    | '/job-match'
    | '/login'
    | '/mock-interview'
    | '/privacy'
    | '/reset-password'
    | '/result'
    | '/resume-score-checker'
    | '/software-engineer-resume-template'
    | '/terms'
    | '/upload'
    | '/auth/callback'
    | '/dashboard/history'
    | '/dashboard/interviews'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/saved'
    | '/dashboard/security'
    | '/interview-report/$id'
    | '/mobile/beta-program'
    | '/mobile/insights'
    | '/mobile/request-feature'
    | '/mobile/tools'
    | '/report/$id'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiCoverLetterGeneratorRoute: typeof AiCoverLetterGeneratorRoute
  AiInterviewQuestionsRoute: typeof AiInterviewQuestionsRoute
  AtsResumeCheckerRoute: typeof AtsResumeCheckerRoute
  ComingSoonRoute: typeof ComingSoonRoute
  CoverLetterRoute: typeof CoverLetterRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DataAnalystResumeTemplateRoute: typeof DataAnalystResumeTemplateRoute
  DataDeletionRoute: typeof DataDeletionRoute
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  FresherResumeTemplateRoute: typeof FresherResumeTemplateRoute
  HowItWorksRoute: typeof HowItWorksRoute
  JobMatchRoute: typeof JobMatchRoute
  LoginRoute: typeof LoginRoute
  MockInterviewRoute: typeof MockInterviewRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResultRoute: typeof ResultRoute
  ResumeScoreCheckerRoute: typeof ResumeScoreCheckerRoute
  SoftwareEngineerResumeTemplateRoute: typeof SoftwareEngineerResumeTemplateRoute
  TermsRoute: typeof TermsRoute
  UploadRoute: typeof UploadRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  InterviewReportIdRoute: typeof InterviewReportIdRoute
  MobileBetaProgramRoute: typeof MobileBetaProgramRoute
  MobileInsightsRoute: typeof MobileInsightsRoute
  MobileRequestFeatureRoute: typeof MobileRequestFeatureRoute
  MobileToolsRoute: typeof MobileToolsRoute
  ReportIdRoute: typeof ReportIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software-engineer-resume-template': {
      id: '/software-engineer-resume-template'
      path: '/software-engineer-resume-template'
      fullPath: '/software-engineer-resume-template'
      preLoaderRoute: typeof SoftwareEngineerResumeTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-score-checker': {
      id: '/resume-score-checker'
      path: '/resume-score-checker'
      fullPath: '/resume-score-checker'
      preLoaderRoute: typeof ResumeScoreCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-interview': {
      id: '/mock-interview'
      path: '/mock-interview'
      fullPath: '/mock-interview'
      preLoaderRoute: typeof MockInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-match': {
      id: '/job-match'
      path: '/job-match'
      fullPath: '/job-match'
      preLoaderRoute: typeof JobMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fresher-resume-template': {
      id: '/fresher-resume-template'
      path: '/fresher-resume-template'
      fullPath: '/fresher-resume-template'
      preLoaderRoute: typeof FresherResumeTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-deletion': {
      id: '/data-deletion'
      path: '/data-deletion'
      fullPath: '/data-deletion'
      preLoaderRoute: typeof DataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-analyst-resume-template': {
      id: '/data-analyst-resume-template'
      path: '/data-analyst-resume-template'
      fullPath: '/data-analyst-resume-template'
      preLoaderRoute: typeof DataAnalystResumeTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cover-letter': {
      id: '/cover-letter'
      path: '/cover-letter'
      fullPath: '/cover-letter'
      preLoaderRoute: typeof CoverLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ats-resume-checker': {
      id: '/ats-resume-checker'
      path: '/ats-resume-checker'
      fullPath: '/ats-resume-checker'
      preLoaderRoute: typeof AtsResumeCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-interview-questions': {
      id: '/ai-interview-questions'
      path: '/ai-interview-questions'
      fullPath: '/ai-interview-questions'
      preLoaderRoute: typeof AiInterviewQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-cover-letter-generator': {
      id: '/ai-cover-letter-generator'
      path: '/ai-cover-letter-generator'
      fullPath: '/ai-cover-letter-generator'
      preLoaderRoute: typeof AiCoverLetterGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/report/$id': {
      id: '/report/$id'
      path: '/report/$id'
      fullPath: '/report/$id'
      preLoaderRoute: typeof ReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/tools': {
      id: '/mobile/tools'
      path: '/mobile/tools'
      fullPath: '/mobile/tools'
      preLoaderRoute: typeof MobileToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/request-feature': {
      id: '/mobile/request-feature'
      path: '/mobile/request-feature'
      fullPath: '/mobile/request-feature'
      preLoaderRoute: typeof MobileRequestFeatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/insights': {
      id: '/mobile/insights'
      path: '/mobile/insights'
      fullPath: '/mobile/insights'
      preLoaderRoute: typeof MobileInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/beta-program': {
      id: '/mobile/beta-program'
      path: '/mobile/beta-program'
      fullPath: '/mobile/beta-program'
      preLoaderRoute: typeof MobileBetaProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview-report/$id': {
      id: '/interview-report/$id'
      path: '/interview-report/$id'
      fullPath: '/interview-report/$id'
      preLoaderRoute: typeof InterviewReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/security': {
      id: '/dashboard/security'
      path: '/security'
      fullPath: '/dashboard/security'
      preLoaderRoute: typeof DashboardSecurityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/saved': {
      id: '/dashboard/saved'
      path: '/saved'
      fullPath: '/dashboard/saved'
      preLoaderRoute: typeof DashboardSavedRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/interviews': {
      id: '/dashboard/interviews'
      path: '/interviews'
      fullPath: '/dashboard/interviews'
      preLoaderRoute: typeof DashboardInterviewsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardInterviewsRoute: typeof DashboardInterviewsRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSavedRoute: typeof DashboardSavedRoute
  DashboardSecurityRoute: typeof DashboardSecurityRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardInterviewsRoute: DashboardInterviewsRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSavedRoute: DashboardSavedRoute,
  DashboardSecurityRoute: DashboardSecurityRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiCoverLetterGeneratorRoute: AiCoverLetterGeneratorRoute,
  AiInterviewQuestionsRoute: AiInterviewQuestionsRoute,
  AtsResumeCheckerRoute: AtsResumeCheckerRoute,
  ComingSoonRoute: ComingSoonRoute,
  CoverLetterRoute: CoverLetterRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DataAnalystResumeTemplateRoute: DataAnalystResumeTemplateRoute,
  DataDeletionRoute: DataDeletionRoute,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  FresherResumeTemplateRoute: FresherResumeTemplateRoute,
  HowItWorksRoute: HowItWorksRoute,
  JobMatchRoute: JobMatchRoute,
  LoginRoute: LoginRoute,
  MockInterviewRoute: MockInterviewRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResultRoute: ResultRoute,
  ResumeScoreCheckerRoute: ResumeScoreCheckerRoute,
  SoftwareEngineerResumeTemplateRoute: SoftwareEngineerResumeTemplateRoute,
  TermsRoute: TermsRoute,
  UploadRoute: UploadRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  InterviewReportIdRoute: InterviewReportIdRoute,
  MobileBetaProgramRoute: MobileBetaProgramRoute,
  MobileInsightsRoute: MobileInsightsRoute,
  MobileRequestFeatureRoute: MobileRequestFeatureRoute,
  MobileToolsRoute: MobileToolsRoute,
  ReportIdRoute: ReportIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
